#if UNITY_ANDROID

using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;

using GooglePlayGames.Android.Java;
using GooglePlayGames.Utils;

using Logger = GooglePlayGames.Utils.Logger;

using ACC   = GooglePlayGames.Api.SavedGame.ConflictCallback;
using ACRS  = GooglePlayGames.Api.SavedGame.ConflictResolutionStrategy;
using ADS   = GooglePlayGames.Api.DataSource;
using AISGC = GooglePlayGames.Api.SavedGame.ISavedGameClient;
using AISGM = GooglePlayGames.Api.SavedGame.ISavedGameMetadata;
using ASGMU = GooglePlayGames.Api.SavedGame.SavedGameMetadataUpdate;
using ASGRS = GooglePlayGames.Api.SavedGame.SavedGameRequestStatus;
using ASUS  = GooglePlayGames.Api.SavedGame.SelectUiStatus;

using APGC = GooglePlayGames.Android.PlayGamesClient;
using ASM  = GooglePlayGames.Android.SnapshotMetadata;

using JSCI = GooglePlayGames.Android.Java.SnapshotsClient.Instance;

namespace GooglePlayGames.Android {

    internal sealed class SavedGameClient : AISGC {
        
        private static readonly Regex s_validFilename = new(@"\A[a-zA-Z0-9-._~]{1,100}\Z");

        internal static bool IsValidFilename(string filename)
        {
            if (filename == null) return false;
            return s_validFilename.IsMatch(filename);
        }

        public SavedGameClient(APGC androidClient)
        {
            JPlayClient     = androidClient;
            JSnapshotClient = PlayGames.JGetSnapshotsClient();
        }

        internal APGC JPlayClient     { get; }
        internal JSCI JSnapshotClient { get; }

        private void InternalOpen(string filename, ADS source, ACRS strategy, bool prefetch, ACC onConflict, Action<ASGRS, AISGM> onComplete)
        {
            var jPolicy = Utility.ToJavaResolutionPolicy(strategy);
            using var jTask = JSnapshotClient.JOpen(filename, create: true, jPolicy);
            jTask.JAddOnSuccessListener(jData => {
                if (!jData.IsConflict()) {
                    var snap = null as ASM;
                    using (var jSnapshot = jData.JGetData()) {
                        using var jMetadata = jSnapshot.JFreeze();
                        snap = new ASM(jMetadata);
                    }
                    onComplete(ASGRS.Success, snap);
                    return;
                }
                using var jConflict = jData.JGetConflict();
                var original = new ASM(jConflict.JGetSnapshot());
                var unmerged = new ASM(jConflict.JGetConflictingSnapshot());
                void retry() => InternalOpen(filename, source, strategy, prefetch, onConflict, onComplete);
                var resolver = new ConflictResolver(this, JSnapshotClient, jConflict, original, unmerged, onComplete, retry);
                var originalBytes = original.JSnapshotContents.ReadFully();
                var unmergedBytes = unmerged.JSnapshotContents.ReadFully();
                onConflict(resolver, original, originalBytes, unmerged, unmergedBytes);
            }).JAddOnFailureListener(jException => {
                Logger.d("InternalOpen has failed: " + jException.JToString());
                onComplete(JPlayClient.GetSavedGameRequestStatus(), null);
            });
        }

        #region ISavedGameClient implementation

        public void CommitUpdate(AISGM metadata, ASGMU update, byte[] bytes, Action<ASGRS, AISGM> callback)
        {
            Misc.CheckNotNull(metadata);
            Misc.CheckNotNull(bytes);
            callback = Utility.ToUiAction(callback);

            if (metadata is not ASM casted) {
                Logger.e("Encountered metadata that was not generated by this ISavedGameClient");
                callback(ASGRS.BadInputError, null);
                return;
            }

            if (!casted.IsOpen) {
                Logger.e("This method requires an open ISavedGameMetadata.");
                callback(ASGRS.BadInputError, null);
                return;
            }

            if (!casted.JSnapshotContents.WriteBytes(bytes)) {
                Logger.e("This method requires an open ISavedGameMetadata.");
                callback(ASGRS.BadInputError, null);
                return;
            }

            using var jUpdate = Utility.ToJavaSnapshotMetadataChangeUpdate(update);
            using var jTask   = JSnapshotClient.JCommitAndClose(casted.JSnapshot, jUpdate);
            jTask.JAddOnSuccessListener(dispose: false, jMetadata => {
                Logger.d("commitAndClose.succeed");
                callback(ASGRS.Success, new ASM(jMetadata, null));
            }).JAddOnFailureListener(exception => {
                Logger.e("commitAndClose.failed: " + exception.JToString());
                callback(JPlayClient.GetSavedGameRequestStatus(), null);
            });
        }

        public void Delete(AISGM metadata)
        {
            var casted = metadata as ASM;
            Misc.CheckNotNull(casted);
            using (JSnapshotClient.JDelete(casted.JSnapshotMetadata)) {
                // No-op
            }
        }

        public void FetchAllSavedGames(ADS source, Action<ASGRS, List<AISGM>> callback)
        {
            callback = Utility.ToUiAction(callback);

            using var jTask = JSnapshotClient.JLoad(reload: source == ADS.ReadNetworkOnly);
            jTask.JAddOnSuccessListener(jData => {
                using var jSnapshots = jData.JGet();
                var count = jSnapshots.GetCount();
                var result = new List<AISGM>();
                for (var i = 0; i < count; i += 1) {
                    var element = null as ASM;
                    using (var jMetadata = jSnapshots.JGet(i)) {
                        element = new ASM(jMetadata.JFreeze(), null);
                    }
                    result.Add(element);
                }
                callback(ASGRS.Success, result);
            }).JAddOnFailureListener(jException => {
                Logger.d("FetchAllSavedGames failed: " + jException.JToString());
                callback(JPlayClient.GetSavedGameRequestStatus(), new List<AISGM>());
            });
        }

        public void OpenWithAutomaticConflictResolution(string filename, ADS source, ACRS strategy, Action<ASGRS, AISGM> completedCallback)
        {
            Misc.CheckNotNull(filename);
            completedCallback = Utility.ToUiAction(completedCallback);

            var prefetchDataOnConflict = false;
            ACC conflictCallback = (resolver, original, originalData, unmerged, unmergedData) => {
                switch (strategy) {
                    case ACRS.UseOriginal:
                        resolver.ChooseMetadata(original);
                        return;
                    case ACRS.UseUnmerged:
                        resolver.ChooseMetadata(unmerged);
                        return;
                    case ACRS.UseLongestPlaytime:
                        if (original.PlayedTime >= unmerged.PlayedTime) {
                            resolver.ChooseMetadata(original);
                        } else {
                            resolver.ChooseMetadata(unmerged);
                        }
                        return;
                    default:
                        Logger.e("Unhandled strategy " + strategy);
                        completedCallback(ASGRS.InternalError, null);
                        return;
                }
            };
            conflictCallback = Utility.ToUiDelegate(conflictCallback);

            if (!IsValidFilename(filename)) {
                Logger.e("Received invalid filename: " + filename);
                completedCallback(ASGRS.BadInputError, null);
                return;
            }

            InternalOpen(filename, source, strategy, prefetchDataOnConflict, conflictCallback, completedCallback);
        }

        public void OpenWithManualConflictResolution(string filename, ADS source, bool prefetchDataOnConflict, ACC conflictCallback, Action<ASGRS, AISGM> completedCallback)
        {
            Misc.CheckNotNull(filename);
            conflictCallback  = Utility.ToUiDelegate(conflictCallback);
            completedCallback = Utility.ToUiAction(completedCallback);

            if (!IsValidFilename(filename)) {
                Logger.e("Received invalid filename: " + filename);
                completedCallback(ASGRS.BadInputError, null);
                return;
            }

            InternalOpen(filename, source, ACRS.UseManual, prefetchDataOnConflict, conflictCallback, completedCallback);
        }

        public void ReadBinaryData(AISGM metadata, Action<ASGRS, byte[]> completedCallback)
        {
            Misc.CheckNotNull(metadata);
            completedCallback = Utility.ToUiAction(completedCallback);

            if (metadata is not ASM casted) {
                Logger.e("Encountered metadata that was not generated by this ISavedGameClient");
                completedCallback(ASGRS.BadInputError, null);
                return;
            }

            if (!casted.IsOpen) {
                Logger.e("This method requires an open ISavedGameMetadata.");
                completedCallback(ASGRS.BadInputError, null);
                return;
            }

            var data = casted.JSnapshotContents.ReadFully();
            if (data == null) {
                completedCallback(ASGRS.BadInputError, null);
            } else {
                completedCallback(ASGRS.Success, data);
            }
        }

        public void ShowSelectSavedGameUI(string uiTitle, uint maxDisplayedSavedGames, bool showCreateSaveUI, bool showDeleteSaveUI, Action<ASUS, AISGM> callback)
        {
            Misc.CheckNotNull(uiTitle);
            callback = Utility.ToUiAction(callback);

            if (maxDisplayedSavedGames <= 0) {
                Logger.e("maxDisplayedSavedGames must be greater than 0");
                callback(ASUS.BadInputError, null);
                return;
            }

            // HelperFragment.ShowSelectSnapshotUI(showCreateSaveUI, showDeleteSaveUI, (int)maxDisplayedSavedGames, uiTitle, callback);
        }

        #endregion ISavedGameClient implementation

    }

}

#endif