#if UNITY_ANDROID

using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;

using GooglePlayGames.Android.Java.Extensions;
using GooglePlayGames.Utils;

using Logger = GooglePlayGames.Utils.Logger;

using ACC   = GooglePlayGames.Api.SavedGame.ConflictCallback;
using ACRS  = GooglePlayGames.Api.SavedGame.ConflictResolutionStrategy;
using ADS   = GooglePlayGames.Api.DataSource;
using AISGC = GooglePlayGames.Api.SavedGame.ISavedGameClient;
using AISGM = GooglePlayGames.Api.SavedGame.ISavedGameMetadata;
using ASGMU = GooglePlayGames.Api.SavedGame.SavedGameMetadataUpdate;
using ASGRS = GooglePlayGames.Api.SavedGame.SavedGameRequestStatus;
using ASUS  = GooglePlayGames.Api.SavedGame.SelectUiStatus;

using APGC = GooglePlayGames.Android.PlayGamesClient;
using ASGC = GooglePlayGames.Android.SavedGameClient;
using ASM  = GooglePlayGames.Android.SnapshotMetadata;

using JPG  = GooglePlayGames.Android.Java.PlayGames;
using JSCI = GooglePlayGames.Android.Java.SnapshotsClient.Instance;

namespace GooglePlayGames.Android {

    internal sealed class SavedGameClient : AISGC {
        
        private static readonly Regex s_validFilename = new(@"\A[a-zA-Z0-9-._~]{1,100}\Z");

        internal static bool IsValidFilename(string filename)
        {
            if (filename == null) return false;
            return s_validFilename.IsMatch(filename);
        }

        public SavedGameClient(APGC androidClient)
        {
            JPlayClient     = androidClient;
            JSnapshotClient = JPG.JGetSnapshotsClient();
        }

        internal APGC JPlayClient     { get; }
        internal JSCI JSnapshotClient { get; }

        private void InternalOpen(string filename, ADS source, ACRS strategy, bool prefetch, ACC onConflict, Action<ASGRS, AISGM> onComplete)
        {
            const string method = "InternalOpen(string, DataSource, ConflictResolutionStrategy, bool, ConflictCallback, Action<ResponseStatus, ISavedGameMetadata>)";
            Logger.t($"AND: Calling {method}");

                  var jPolicy = Utility.ToJavaResolutionPolicy(strategy);
            using var jTask   = JSnapshotClient.JOpen(filename, create: true, jPolicy);
            jTask.JAddOnSuccessListener(jData => {
                Logger.t($"AND: Success {method}");

                if (!jData.IsConflict()) {
                    var snap = null as ASM;
                    using (var jSnapshot = jData.JGetData()) {
                        using var jMetadata = jSnapshot.JFreeze();
                        snap = new ASM(jMetadata);
                    }
                    onComplete.Invoke(ASGRS.Success, snap);
                    return;
                }

                using var jConflict = jData.JGetConflict();
                      var original = new ASM(jConflict.JGetSnapshot());
                      var unmerged = new ASM(jConflict.JGetConflictingSnapshot());
                void retry() => InternalOpen(filename, source, strategy, prefetch, onConflict, onComplete);
                var resolver = new ConflictResolver(this, JSnapshotClient, jConflict, original, unmerged, onComplete, retry);
                
                var originalBytes = original.JSnapshotContents.ReadFully();
                var unmergedBytes = unmerged.JSnapshotContents.ReadFully();
                onConflict.Invoke(resolver, original, originalBytes, unmerged, unmergedBytes);
            }).JAddOnFailureListener(jException => {
                Logger.t($"AND: Failure {method}");
                Logger.w($"AND: {jException.JToString()}");
                onComplete.Invoke(JPlayClient.GetSavedGameRequestStatus(), null);
            });
        }

        #region ISavedGameClient implementation

        public void CommitUpdate(AISGM metadata, ASGMU update, byte[] bytes, Action<ASGRS, AISGM> callback)
        {
            const string method = "ISavedGameClient.CommitUpdate(ISavedGameMetadata, SavedGameMetadataUpdate, byte[], Action<ResponseStatus, ISavedGameMetadata>)";
            Logger.t($"AND: Calling {method}");

            Misc.CheckNotNull(metadata);
            Misc.CheckNotNull(bytes);
            callback = Utility.ToUiAction(callback);

            if (metadata is not ASM casted) {
                Logger.e("AND: Encountered metadata that was not generated by this ISavedGameClient");
                callback.Invoke(ASGRS.BadInputError, null);
                return;
            }

            if (!casted.IsOpen) {
                Logger.e("AND: This method requires an open ISavedGameMetadata");
                callback.Invoke(ASGRS.BadInputError, null);
                return;
            }

            if (!casted.JSnapshotContents.WriteBytes(bytes)) {
                Logger.e("AND: This method requires an open ISavedGameMetadata");
                callback.Invoke(ASGRS.BadInputError, null);
                return;
            }

            using var jUpdate = Utility.ToJavaSnapshotMetadataChangeUpdate(update);
            using var jTask   = JSnapshotClient.JCommitAndClose(casted.JSnapshot, jUpdate);
            jTask.JAddOnSuccessListener(dispose: false, jMetadata => {
                Logger.t($"AND: Success {method}");
                callback.Invoke(ASGRS.Success, new ASM(jMetadata, null));
            }).JAddOnFailureListener(jException => {
                Logger.t($"AND: Failure {method}");
                Logger.d("AND: " + jException.JToString());
                callback.Invoke(JPlayClient.GetSavedGameRequestStatus(), null);
            });
        }

        public void Delete(AISGM metadata)
        {
            const string method = "ISavedGameClient.Delete(ISavedGameMetadata)";
            Logger.t($"AND: Calling {method}");

            var casted = metadata as ASM;
            Misc.CheckNotNull(casted);

            using (JSnapshotClient.JDelete(casted.JSnapshotMetadata)) {
                // No-op
            }
        }

        public void FetchAllSavedGames(ADS source, Action<ASGRS, List<AISGM>> callback)
        {
            const string method = "ISavedGameClient.FetchAllSavedGames(DataSource, Action<ResponseStatus, List<ISavedGameMetadata>>)";
            Logger.t($"AND: Calling {method}");

            callback = Utility.ToUiAction(callback);

            using var jTask = JSnapshotClient.JLoad(reload: source == ADS.ReadNetworkOnly);
            jTask.JAddOnSuccessListener(jData => {
                Logger.t($"AND: Success {method}");
                using var jSnapshots = jData.JGet();
                      var count      = jSnapshots.GetCount();
                      var result     = new List<AISGM>();
                for (var i = 0; i < count; i += 1) {
                    var element = null as ASM;
                    using (var jMetadata = jSnapshots.JGet(i)) {
                        element = new ASM(jMetadata.JFreeze(), null);
                    }
                    result.Add(element);
                }
                callback.Invoke(ASGRS.Success, result);
            }).JAddOnFailureListener(jException => {
                Logger.t($"AND: Failure {method}");
                Logger.d("AND: " + jException.JToString());
                callback.Invoke(JPlayClient.GetSavedGameRequestStatus(), new List<AISGM>());
            });
        }

        public void OpenWithAutomaticConflictResolution(string filename, ADS source, ACRS strategy, Action<ASGRS, AISGM> completedCallback)
        {
            const string method = "ISavedGameClient.OpenWithAutomaticConflictResolution(string, DataSource, ConflictResolutionStrategy, Action<ResponseStatus, ISavedGameMetadata>)";
            Logger.t($"AND: Calling {method}");

            Misc.CheckNotNull(filename);
            completedCallback = Utility.ToUiAction(completedCallback);

            var prefetch = false;
            ACC onConflict = (resolver, original, originalData, unmerged, unmergedData) => {
                switch (strategy) {
                    case ACRS.UseOriginal:
                        resolver.ChooseMetadata(original);
                        return;
                    case ACRS.UseUnmerged:
                        resolver.ChooseMetadata(unmerged);
                        return;
                    case ACRS.UseLongestPlaytime:
                        if (original.PlayedTime >= unmerged.PlayedTime) {
                            resolver.ChooseMetadata(original);
                        } else {
                            resolver.ChooseMetadata(unmerged);
                        }
                        return;
                    default:
                        Logger.e("AND: Unhandled strategy " + strategy);
                        completedCallback(ASGRS.InternalError, null);
                        return;
                }
            };
            onConflict = Utility.ToUiDelegate(onConflict);

            if (!IsValidFilename(filename)) {
                Logger.e("AND: Received invalid filename: " + filename);
                completedCallback(ASGRS.BadInputError, null);
                return;
            }

            InternalOpen(filename, source, strategy, prefetch, onConflict, completedCallback);
        }

        public void OpenWithManualConflictResolution(string filename, ADS source, bool prefetch, ACC onConflict, Action<ASGRS, AISGM> onCompleted)
        {
            const string method = "ISavedGameClient.OpenWithManualConflictResolution(string, DataSource, bool, ConflictCallback, Action<ResponseStatus, ISavedGameMetadata>)";
            Logger.t($"AND: Calling {method}");

            Misc.CheckNotNull(filename);
            onConflict  = Utility.ToUiDelegate(onConflict);
            onCompleted = Utility.ToUiAction(onCompleted);

            if (!IsValidFilename(filename)) {
                Logger.e("AND: Received invalid filename: " + filename);
                onCompleted(ASGRS.BadInputError, null);
                return;
            }

            InternalOpen(filename, source, ACRS.UseManual, prefetch, onConflict, onCompleted);
        }

        public void ReadBinaryData(AISGM metadata, Action<ASGRS, byte[]> callback)
        {
            const string method = "ISavedGameClient.ReadBinaryData(ISavedGameMetadata, Action<ResponseStatus, byte[]>)";
            Logger.t($"AND: Calling {method}");

            Misc.CheckNotNull(metadata);
            callback = Utility.ToUiAction(callback);

            if (metadata is not ASM casted) {
                Logger.e("AND: Encountered metadata that was not generated by this ISavedGameClient");
                callback.Invoke(ASGRS.BadInputError, null);
                return;
            }

            if (!casted.IsOpen) {
                Logger.e("AND: This method requires an open ISavedGameMetadata.");
                callback.Invoke(ASGRS.BadInputError, null);
                return;
            }

            var data = casted.JSnapshotContents.ReadFully();
            if (data == null) {
                callback.Invoke(ASGRS.BadInputError, null);
            } else {
                callback.Invoke(ASGRS.Success, data);
            }
        }

        public void ShowSelectSavedGameUI(string uiTitle, uint maxDisplayedSavedGames, bool showCreateSaveUI, bool showDeleteSaveUI, Action<ASUS, AISGM> callback)
        {
            const string method = "ISavedGameClient.ShowSelectSavedGameUI(string, uint, bool, bool, Action<SelectUIStatus, ISavedGameMetadata>)";
            Logger.t($"AND: Calling {method}");

            Misc.CheckNotNull(uiTitle);
            callback = Utility.ToUiAction(callback);

            if (maxDisplayedSavedGames <= 0) {
                Logger.w("AND: maxDisplayedSavedGames must be greater than 0");
                callback.Invoke(ASUS.BadInputError, null);
                return;
            }

            // HelperFragment.ShowSelectSnapshotUI(showCreateSaveUI, showDeleteSaveUI, (int)maxDisplayedSavedGames, uiTitle, callback);
        }

        #endregion ISavedGameClient implementation

        #region Object implementation

        public override string ToString() => $"SavedGameClient(playClient: {JPlayClient}, snapClient: {JSnapshotClient})";
        public override int GetHashCode() => HashCode.Combine(JPlayClient, JSnapshotClient);

        public override bool Equals(object other)
        {
            if (other is not ASGC it) return false;
            return JPlayClient    .Equals(it.JPlayClient) &&
                   JSnapshotClient.Equals(it.JSnapshotClient);
        }

        #endregion Object implementation

    }

}

#endif